### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by JGSolutions** [vision89/lazy-grid-style#1]
Is this grid component responsive?

**Comment by vision89** [comment]
Hey Jerry,

```
 I'm thinking the answer is no but honestly I'm not sure what you're
```

asking there.  Do you mean can the columns be resized dynamically?  If so
there's nothing in it to do that.  It's really just css to easily make rows
and columns and it's in an element so that it can be put included in other
elements easily.  By all means let me know if there's something I can do to
make it better and I'll see what I can do.

Take Care,
Dustin

**Comment by JGSolutions** [comment]
Hey,

If you look at bootstrap or foundation's grid they have columns that you can specify for screens for ex:

In your component you have

col-6

Other grid systems options are like: col-s-6 (for small screens) (col-m-6) for medium screen

for example this: https://github.com/The5heepDev/iron-grid

**Comment by vision89** [comment]
I see, okay I think I can handle an update like that :-)  Just so you know
it is probably going to be over a week before I can update it.  I'm going
to be on the road all next week for work, and well, it's just a busy time
of year all together.  It's on my list though!

Thanks!
Dustin

**Comment by JGSolutions** [comment]
Maybe don't even bother with this component unless there is something or idea that is really different.

I found this one that is pretty good and tested quickly
https://customelements.io/vguillou/g-r-i-d/

Also this:
https://customelements.io/myfreeweb/mason-ry/

**Comment by vision89** [comment]
Okay, yes both of those look like they have more features you must need.
Good luck with the project you're using it for!

Take Care,
Dustin

**Comment by vision89** [comment]
I'm closing this since it does all I need it to do at the moment, and since Jerry is moving to a different grid system.
